//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCalendar.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int event_id { get; set; }
        public string event_name { get; set; }
        public string event_desc { get; set; }
        public Nullable<System.DateTime> event_datetimeUTC { get; set; }
        public string event_location { get; set; }
        public int source_id { get; set; }
    
        public virtual Sources Sources { get; set; }
    }
}
