//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCalendar.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Sources
    {
        public int user_id { get; set; }
        public int source_id { get; set; }
        public System.DateTime dateRegistered { get; set; }
    
        public virtual Sources Sources { get; set; }
        public virtual Users Users { get; set; }
    }
}
